COUNTRIES = ["PHILIPPINES"]
REGIONS = [
    "CORDILLERA ADMINISTRATIVE REGION (CAR)",
    "REGION I (ILOCOS REGION)",
    "REGION II (CAGAYAN VALLEY)",
    "REGION III (CENTRAL LUZON)",
    "REGION IV-A (CALABARZON)",
    "REGION IV-B (MIMAROPA)",
    "MIMAROPA REGION",
    "REGION V (BICOL REGION)",
    "REGION VI (WESTERN VISAYAS)",
    "REGION VII (CENTRAL VISAYAS)",
    "REGION VIII (EASTERN VISAYAS)",
    "REGION IX (ZAMBOANGA PENINSULA)",
    "REGION X (NORTHERN MINDANAO)",
    "REGION XI (DAVAO REGION)",
    "REGION XII (SOCCSKSARGEN)",
    "REGION XIII (CARAGA)",
    "AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)",
    "CORDILLERA ADMINISTRATIVE REGION (CAR)",
]

REGIONS_AND_COUNTRIES = REGIONS + COUNTRIES